### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin-python-sdk#4]
I would like to start exploring what we need in order to make this repo public and usable as an experimental SDK for Spin:

- [x] self-contained Spin plugin (i.e. `spin py2wasm`) — #7 
- [x] minimal Spin SDK support (HTTP, outbound HTTP, outbound Redis)
- [x] template for an HTTP application / component — #5 
- [x] documentation — #6 
- [ ] type hints — #9 
- [x] example adding external packages (already in the example)

cc @dicej @karthik2804
